# Generated by Django 5.0.4 on 2024-04-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.ImageField(upload_to='art/')),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
